http:
  port: 8000

apiEndpoints:
  users:
    host: localhost
    paths:
      - /api/users/login

  users-protected:
    host: localhost
    paths:
      - /api/users/profile
      - /api/users/update
      - /api/admin/get-users
      - /api/admin/dashboard-info

  documents:
    host: localhost
    paths:
      - /api/documents

serviceEndpoints:
  user-service:
    url: ${USER_SERVICE_URL}
  document-service:
    url: ${DOCUMENT_SERVICE_URL}

policies:
  - jwt
  - proxy
  - cors
  - rate-limit

pipelines:
  user-pipeline:
    apiEndpoints:
      - users
    policies:
      - cors:
          - action:
              origin: "http://localhost:5173"
              methods: "GET,POST,OPTIONS"
              credentials: true
              allowedHeaders: "Origin, X-Requested-With, Content-Type, Accept, Authorization"
      - proxy:
          - action:
              serviceEndpoint: user-service
              changeOrigin: true

  user-protected-pipeline:
    apiEndpoints:
      - users-protected
    policies:
      - cors:
          - action:
              origin: "http://localhost:5173"
              methods: "GET,POST,PUT,DELETE,OPTIONS"
              credentials: true
              allowedHeaders: "Origin, X-Requested-With, Content-Type, Accept, Authorization"
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentials: true
              credentialsRequired: true
              checkCredentialExistence: false # to change

      - proxy:
          - action:
              serviceEndpoint: user-service
              changeOrigin: true

  document-pipeline:
    apiEndpoints:
      - documents
    policies:
      - cors:
          - action:
              origin: "http://localhost:5173"
              methods: "GET,POST,PUT,DELETE,OPTIONS"
              credentials: true
              allowedHeaders: "Origin, X-Requested-With, Content-Type, Accept, Authorization"
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentials: true
              credentialsRequired: true
      - proxy:
          - action:
              serviceEndpoint: document-service
              changeOrigin: true
