http:
  port: 8000
apiEndpoints:
  users:
    host: localhost
    paths:
      - /api/users/login
  users-protected:
    host: localhost
    paths:
      - /api/users/profile
      - /api/users/update
  documents:
    host: localhost
    paths:
      - /api/documents
  
serviceEndpoints:
  user-service:
    url: ${USER_SERVICE_URL}
  document-service:
    url: ${DOCUMENT_SERVICE_URL}

policies:
  - jwt
  - proxy
  - cors
  - rate-limit
  - key-auth
  - expression
  - log

pipelines:
  user-pipeline:
    apiEndpoints:
      - users
    policies:
      - cors:
          - action:
              origin: "*"
      - proxy:
          - action:
              serviceEndpoint: user-service
              changeOrigin: true

  user-protected-pipeline:
    apiEndpoints:
      - users-protected
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentials: true
              credentialsRequired: true
      - proxy:
          - action:
              serviceEndpoint: user-service
              changeOrigin: true

  document-pipeline:
    apiEndpoints:
      - documents
    policies:
      - jwt:
          - action:
              secretOrPublicKey: 'secret'
              checkCredentials: true
              credentialsRequired: true
      - proxy:
          - action:
              serviceEndpoint: document-service
              changeOrigin: true
